name: iOS test
env:
      ENVTEMP: ${{ secrets.TESTOTESTO }}
on:
  push:
    branches: [ "main" ]  
jobs:
  check: 
    name: Just check
    runs-on: ubuntu-latest
    environment: testEnv
    steps: 
    - shell: bash
      run: | 
            echo "$ENVTEMP"
            echo "---"
            echo "$TEST"
            
  tests: 
    name: iOS test
    runs-on: macos-latest    
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - name: info
        run: | 
            ls -la
            xcodebuild -version
            ruby -v
      - name: test
        run: | 
            device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
            echo "$device" 
            echo "4-7 minutes for testing - commented"
#            xcodebuild -project EmptyProject/EmptyProject.xcodeproj -scheme EmptyProject  -destination "platform=iOS Simulator,name=$device" test
            

